apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.4
          args: 
            - "start"
            - "--db=postgres"
            - "--db-url=jdbc:postgresql://postgres:5432/petdb"
            - "--hostname-strict=false"
            - "--hostname-strict-https=false"
            - "--http-enabled=true"
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres:5432/petdb
            - name: KC_DB_USERNAME
              valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: POSTGRES_PASSWORD
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import/realm-export.json
              subPath: realm-export.json
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm-config
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc 