services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/pipis/.kube:/root/.kube:ro
      - /snap/bin/kubectl:/usr/local/bin/kubectl
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
