apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cGV0ZGI=         # petdb (base64)
  POSTGRES_USER: cGV0dXNlcg==   # petuser (base64)
  POSTGRES_PASSWORD: cGV0cGFzcw== # petpass (base64)
