---
- name: Deploy Complete DevOps Pets Application
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Check if kubectl is available
      command: kubectl version --client
      register: kubectl_check
      failed_when: false
      
    - name: Fail if kubectl is not available
      fail:
        msg: "kubectl is not available. Please install kubectl first."
      when: kubectl_check.rc != 0

    - name: Create namespace if it doesn't exist
      command: kubectl create namespace devops-pets --dry-run=client -o yaml | kubectl apply -f -
      register: namespace_result
      failed_when: false

    - name: Deploy PostgreSQL Database
      command: kubectl apply -f ../k8s/postgres/postgres-deployment.yaml
      register: postgres_deployment
      
    - name: Deploy PostgreSQL Service
      command: kubectl apply -f ../k8s/postgres/postgres-service.yaml
      register: postgres_service
      
    - name: Deploy PostgreSQL PVC
      command: kubectl apply -f ../k8s/postgres/postgres-pvc.yaml
      register: postgres_pvc
      
    - name: Deploy PostgreSQL Secret
      command: kubectl apply -f ../k8s/postgres/postgres-secret.yaml
      register: postgres_secret

    - name: Deploy Keycloak
      command: kubectl apply -f ../k8s/keycloak/keycloak-deployment.yaml
      register: keycloak_deployment
      
    - name: Deploy Keycloak Service
      command: kubectl apply -f ../k8s/keycloak/keycloak-service.yaml
      register: keycloak_service

    - name: Deploy MailHog
      command: kubectl apply -f ../k8s/mailhog/mailhog-deployment.yaml
      register: mailhog_deployment
      
    - name: Deploy MailHog Service
      command: kubectl apply -f ../k8s/mailhog/mailhog-service.yaml
      register: mailhog_service

    - name: Deploy Backend Application
      command: kubectl apply -f ../k8s/backend/backend-deployment.yaml
      register: backend_deployment
      
    - name: Deploy Backend Service
      command: kubectl apply -f ../k8s/backend/backend-service.yaml
      register: backend_service

    - name: Wait for PostgreSQL to be ready
      command: kubectl rollout status deployment/postgres --timeout=300s
      register: postgres_rollout
      
    - name: Wait for Keycloak to be ready
      command: kubectl rollout status deployment/keycloak --timeout=300s
      register: keycloak_rollout
      
    - name: Wait for MailHog to be ready
      command: kubectl rollout status deployment/mailhog --timeout=300s
      register: mailhog_rollout
      
    - name: Wait for Backend to be ready
      command: kubectl rollout status deployment/backend --timeout=300s
      register: backend_rollout

    - name: Display deployment status
      debug:
        msg: |
          ========================================
          DEPLOYMENT COMPLETED SUCCESSFULLY!
          ========================================
          
          Services deployed:
          - PostgreSQL Database
          - Keycloak Authentication
          - MailHog Email Service
          - Backend Application
          
          To check services:
          kubectl get services
          
          To check pods:
          kubectl get pods
          
          To access the application:
          kubectl port-forward service/backend 8080:8080 